### ISSUE TITLE
Memleak in function Permitted

### ISSUE THREAD

**Issue by scripter-v** [ryanfaerman/fsm#8]
Hello, Ryan!

I think I found memleak here: https://github.com/ryanfaerman/fsm/blob/v2/fsm.go#L69
After the first goroutine ends with false the function `Permitted` will return and other goroutines will be blocked on write to `outcome` channel and will never end. It seems that select/case with default here would solve the problem.

**Comment by ryanfaerman** [comment]
I know this is an old issue, but I've started using this package again. The parallel guard stuff was neat... but ultimate not required for the sort of simple FSM stuff I've been doing. I've removed the whole concept in `v3`.
